---
# tasks file for aspects_postfix

- include: installPackages.yml
  when: aspects_postfix_enabled
  tags:
  - aspects_postfix

- include: setTemplates.yml
  when: aspects_postfix_enabled
  tags:
  - aspects_postfix