---
- name: Set sasl_passwd file for authed relay
  template:
    src: "etc-postfix-sasl_passwd.j2"
    dest: "/etc/postfix/sasl_passwd"
  register: "sasl_passwd_changed"
  notify: reload postfix
  tags:
  - aspects_postfix
  - aspects_postfix_sasl

- name: Run postmap sasl_passwd
  when: sasl_passwd_changed is defined and sasl_passwd_changed.changed == True
  shell: "postmap /etc/postfix/sasl_passwd"
  notify: reload postfix
  tags:
  - aspects_postfix
  - aspects_postfix_sasl
